<a href="https://colab.research.google.com/github/unna97/Practicing_Numpy/blob/main/100numpyexercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Import the numpy package under the name np (★☆☆)¶


In [ ]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)¶


In [ ]:
print(np.__version__)
np.show_config()
np.__config__.show()

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    libra

3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.array([np.nan] *10)

4. How to find the memory size of any array (★☆☆)


In [ ]:
a = np.random.random(2)
print("memory:",a.nbytes) 
print(np.size(a)*a.itemsize)
print(a.size*a.itemsize)

memory: 16
16
16


5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [ ]:
#np.lookfor('configuration')
#help(np.doc.broadcasting)
#np.doc.broadcasting
#np.info
#??np.add

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)



In [ ]:
almost_null = null_vector.copy() ### Copy is important or else it references memory

In [ ]:
almost_null[4] = 1

In [ ]:
print(almost_null)
print(null_vector)

[nan nan nan nan  1. nan nan nan nan nan]
[nan nan nan nan nan nan nan nan nan nan]


7. Create a vector with values ranging from 10 to 49 (★☆☆)¶



In [ ]:
range_vector = np.arange(10, 50)


8. Reverse a vector (first element becomes last) (★☆☆)


-   *A potentially confusing case is when the step value is negative. In this    case, the defaults for start and stop are swapped. This becomes a convenient   way to reverse an array:*

In [ ]:
reverse_array = range_vector[::-1] ### Remember to copy or it will maipulate the  orignal array as well

In [ ]:
reverse_array[0] = 1


In [ ]:
print(reverse_array)
print(range_vector)

[ 1 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48  1]


9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)


In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)


In [ ]:
a = np.array([1,2,0,0,4,0])
a.nonzero()

(array([0, 1, 4]),)

In [ ]:
np.argwhere(a)

array([[0],
       [1],
       [4]])

11. Create a 3x3 identity matrix (★☆☆)


In [ ]:
#?? np.identity(3)
arr2 = np.eye(4)  # or try with another number like k= -2
print(arr2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


12. Create a 3x3x3 array with random values (★☆☆)


In [ ]:
random_3d = np.random.random((3,3,3))
random_3d

array([[[0.67202502, 0.90145403, 0.95232188],
        [0.74930496, 0.43807983, 0.99118787],
        [0.66238182, 0.84277987, 0.9428566 ]],

       [[0.64617006, 0.62951538, 0.35493794],
        [0.1561103 , 0.46624575, 0.5873587 ],
        [0.55052326, 0.60280862, 0.88034716]],

       [[0.16535496, 0.71043693, 0.90787445],
        [0.78974903, 0.52955751, 0.25892391],
        [0.84826607, 0.7759398 , 0.19651813]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
arr =  np.random.random((10,10))

In [ ]:
arr

array([[0.92286607, 0.25534212, 0.55094724, 0.33683544, 0.36323734,
        0.76631417, 0.05795262, 0.8872348 , 0.03815463, 0.67940802],
       [0.8147125 , 0.3705894 , 0.8972306 , 0.18067697, 0.38667784,
        0.43189633, 0.43907219, 0.66185714, 0.53149996, 0.0646485 ],
       [0.04239942, 0.35774761, 0.21843258, 0.35770097, 0.72857365,
        0.28854973, 0.61525133, 0.81239144, 0.40394594, 0.26321183],
       [0.187072  , 0.13094849, 0.75805805, 0.9256291 , 0.14797953,
        0.10618149, 0.54809149, 0.51805617, 0.15991374, 0.28759796],
       [0.8594521 , 0.77219277, 0.42645838, 0.77976471, 0.92644514,
        0.10375278, 0.4925291 , 0.28720684, 0.77177162, 0.94137561],
       [0.39698074, 0.34945924, 0.74248656, 0.4763959 , 0.83875503,
        0.18534337, 0.07475006, 0.11335749, 0.10313829, 0.73155993],
       [0.46047325, 0.10374798, 0.12072478, 0.49792673, 0.50905923,
        0.19682504, 0.67794116, 0.86079244, 0.38192133, 0.73671957],
       [0.37634634, 0.16203792, 0.4561472

In [ ]:
print(arr.max(), arr.min())


0.9906771058158665 0.038154628361409926


14. Create a random vector of size 30 and find the mean value (★☆☆)




In [ ]:
rand_mean = np.random.random(30)
rand_mean

array([0.01515902, 0.09329158, 0.57248291, 0.99597017, 0.24565998,
       0.83728278, 0.29694876, 0.50747446, 0.1517781 , 0.87030539,
       0.5022373 , 0.9147876 , 0.83686311, 0.31033887, 0.77168424,
       0.45715694, 0.91112373, 0.86852306, 0.35531071, 0.6614872 ,
       0.20386485, 0.13450697, 0.74940226, 0.53791218, 0.73242082,
       0.45456602, 0.72547466, 0.43431999, 0.16103793, 0.50038706])

In [ ]:
rand_mean.mean() == np.mean(rand_mean)

True

In [ ]:
rand_mean.mean()

0.5269919558904187

15. Create a 2d array with 1 on the border and 0 inside (★☆☆)


In [ ]:
arr = np.zeros((3,2))
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.pad(arr,pad_width=1,mode='constant',constant_values=1)

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

16. How to add a border (filled with 0's) around an existing array? (★☆☆)


In [ ]:
np.pad(arr2,1)

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

17. What is the result of the following expression? (★☆☆)
    - 0 * np.nan
    - np.nan == np.nan
    - np.inf > np.nan
    - np.nan - np.nan
    - np.nan in set([np.nan])
    - 0.3 == 3 * 0.1


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)


In [ ]:
diag_ = np.random.random((5,5))

In [ ]:
??diag_.diagonal()

In [ ]:
??np.triu